# Generated by Django 3.1 on 2020-10-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrUserMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Position', models.CharField(max_length=120)),
                ('Worklocation', models.CharField(max_length=120)),
                ('Age', models.IntegerField()),
                ('Startdate', models.DateField()),
                ('salary', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('Edu_qual', models.CharField(max_length=120)),
                ('Experience', models.IntegerField()),
                ('address', models.CharField(max_length=120)),
                ('wrkmail', models.EmailField(max_length=220, unique=True)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leavemgmnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AplyDate', models.DateField()),
                ('leave_status', models.CharField(choices=[('pending', 'pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('None', 'None')], default='None', max_length=120)),
                ('Total_leave', models.IntegerField(default=5)),
            ],
        ),
    ]
