# Generated by Django 3.1 on 2020-10-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaveapp', '0002_auto_20201020_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemgmnt',
            name='Name',
            field=models.CharField(default='athul', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavemgmnt',
            name='desgination',
            field=models.CharField(default='hai', max_length=120),
            preserve_default=False,
        ),
    ]
