# Generated by Django 3.1 on 2020-10-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDatemod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_datt', models.DateField()),
                ('to_datt', models.DateField()),
            ],
        ),
    ]
