# Generated by Django 3.1 on 2020-10-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0002_checkdatemod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckDatemod',
        ),
        migrations.AddField(
            model_name='car',
            name='active_status',
            field=models.IntegerField(default=1),
        ),
    ]
