# Generated by Django 3.1 on 2020-10-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0003_auto_20201008_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_name', models.CharField(max_length=120)),
                ('Age', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=120)),
                ('Address', models.CharField(max_length=120)),
                ('car_id', models.IntegerField()),
                ('orderDate', models.CharField(max_length=120)),
                ('active_state', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ordered', 'ordered'), ('cancelled', 'cancelled')], default='ordered', max_length=120)),
            ],
        ),
    ]
