# Generated by Django 3.1 on 2020-10-12 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
