# Generated by Django 3.1 on 2020-10-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0005_auto_20201012_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.CharField(default='email', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.CharField(default='check', max_length=15),
            preserve_default=False,
        ),
    ]
