# Generated by Django 3.1 on 2020-10-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0006_auto_20201012_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('recieved', 'recieved'), ('cancelled', 'cancelled')], default='ordered', max_length=120),
        ),
    ]
