# Generated by Django 3.1 on 2020-10-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0002_auto_20201008_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Hi_km',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='car',
            name='seat_Select',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')]),
        ),
    ]
