# Generated by Django 3.1 on 2020-10-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0003_auto_20201008_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Hi_km',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
