# Generated by Django 3.1 on 2020-10-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0006_car_hi_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Hi_km',
            field=models.IntegerField(default=None),
        ),
    ]
