# Generated by Django 3.1 on 2020-10-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0008_auto_20201008_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Hi_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
