# Generated by Django 3.1 on 2020-10-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0012_auto_20201008_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Hi_km',
        ),
        migrations.RemoveField(
            model_name='car',
            name='lw_km',
        ),
    ]
