# Generated by Django 3.1 on 2020-10-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0014_auto_20201008_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_high',
            field=models.CharField(max_length=120),
        ),
    ]
