# Generated by Django 3.1 on 2020-10-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0015_auto_20201008_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seat_Select',
            field=models.CharField(max_length=120),
        ),
    ]
